### ISSUE TITLE
Implement script launching

### ISSUE THREAD

**Issue by nLatt** [nLatt/GLaDOS-2023#27]
- [x] Load files via stdin
```sh
$ ./glados < test.scm
```
- [x] Load files via flag
```sh
$ ./glados -f test.scm
$ ./glados --file test.scm
```
- [x] launch repl
```scm
./glados
> (+ 3 2)
```

Additional flags:
- [ ] -d --debug: stops at each scope change and waits for an `enter` keypress

**Comment by nLatt** [comment]
@mindoodoo @virgile-crtl  @audetuczapski @bilou931 si vous avez d'autres idées de flags envoyé les ici1

**Comment by mindoodoo** [comment]
@nLatt Is this issue done ?
