### ISSUE TITLE
Refactor Tests

### ISSUE THREAD

**Issue by mindoodoo** [nLatt/GLaDOS-2023#31]
The goal of this issue is to improve the readability and rigor of the tests in our test suite.

### This means :

- Put **input** and **assertion** values in variables for increased readability
- Make sure test is **not redundant** and **correct**
- Ensure you are declaring **the least variables possible** (try to reuse input values for previous tests where possible)
- Check test name (simplify where possible)

### Files to cleanup :

- [x] ArgsTests.hs -> @nLatt 
- [x] AstTests.hs -> @mindoodoo 
- [x] CptTests.hs -> @mindoodoo 
- [x] TokenTests.hs -> @virgile-crtl 
- [x] ExecTests.hs -> @virgile-crtl 
- [x] ParsingTests.hs -> @audetuczapski 
- [x] TestMain.hs -> @bilou931

**Comment by mindoodoo** [comment]
Please make sure to drop a message on discord and assign yourself if you take up this issue. Also make sure develop has been updated with all latest tests before creating development branch.

**Comment by virgile-crtl** [comment]
refacto test down
